### ISSUE TITLE
Parameter "out_dir" does not work with absolute path

### ISSUE THREAD

**Issue by mldmort** [mkirsche/Jasmine#10]
Hi, 

I would like to write my temporary files to a directory other than my current working directory, however, when I pass an absolute path to "out_dir", the working directory's path is copied in front and Jasmine throws an error.
If I use just the name of a directory, the directory is created in the working directory and the program progresses as normal but the temporary files are written where I'm running my job.

Thanks,
Best regards,

**Comment by mldmort** [comment]
Also I see that there are some files written in my current working directory with names like:
chr22:17066953:INS:0_26680.sam 
chr22:17066953:INS:0_26680.bam
chr22:41939789:INS:0_30784.fastq 

I'm wondering if these temporary files should be written in the working directory or can be written in out_dir path?

Thanks

**Comment by mkirsche** [comment]
Hi, 

Thank you for bringing these issues to my attention!  I totally agree that it should allow for absolute paths and will make that change for my next release.  As for your second question, there is a way to avoid this, but it is a little unintuitive.  Since those files are generated by Iris, their output location is determined by the iris_args parameter, so you could set it by using iris_args=out_dir=iris_output (I will also update this to be something more intuitive).  Are those files still present even after Jasmine/Iris finish running?  They should be temporary files that get removed during Iris' execution unless the process gets interrupted, so if they persist afterwards I would like to look into that.

Thanks!
Melanie

**Comment by mldmort** [comment]
Hi,

The temporary files get deleted after Jasmine finishes running. Thanks for mentioning that it can be fixed by iris arguments.

**Comment by mkirsche** [comment]
Perfect, thanks for confirming that!

**Comment by CharlesARoy** [comment]
Hi Melanie,

Have you had a chance to look at the issue with the out_dir parameter? We recently switched clusters and the high IO rate is problematic for the type of storage where we submit jobs. Being able to specify a different location for the temp files would be really useful.

**Comment by mkirsche** [comment]
Hi,

Jasmine already supports the use of absolute paths for the out_dir parameter, but I also updated the Iris repository to support them as of v1.0.5.  This should be available by updating your version of irissv in bioconda once the change has been propagated there in a day or so.

Best,
Melanie
