### ISSUE TITLE
min_overlap

### ISSUE THREAD

**Issue by Qijie0615** [mkirsche/Jasmine#32]
jasmine can merge SVs across samples and tools.  
i want to merge SVs detected for different samples and different tools, and two overlapping CNVs with RO > 50% were treated as the same region. so i write this command.
jasmine file_list=/bak01/filelist.txt out_file=/bak01/merge_metasv_delly/merge.vcf --min_overlap 0.5 --output_genotypes --default_zero_genotype --leave_breakpoints
I wonder if --min-overlap can be used alone.   because you reply in this question, when using min_overlap,  Jasmine still take "max_dist_linear" or "max_dist" into account to decide  to merge. https://github.com/mkirsche/Jasmine/issues/13. 
thank you !

**Comment by mkirsche** [comment]
Hi,

Thanks for your interest in using Jasmine! In order to use min_overlap alone, I would recommend setting "max_dist_linear=1.0". This will ensure that any two variants which have at least 50% reciprocal overlap will also satisfy the maximum breakpoint distance threshold, essentially removing the threshold from consideration.

I hope that helps!
Melanie
