### ISSUE TITLE
SUPP category in the output

### ISSUE THREAD

**Issue by miyakokodama** [mkirsche/Jasmine#34]
Hi! Thanks for developing Jasmine - it looks really useful! :) 

I have two quick questions; 1) what is the difference between "SUPP" and "SUPP_EXT" in the output, as they appear to be identical? 2) At the moment "SUPP" is defined as string - do you plan on changing this to float in the future for easier filtering? 

Many thanks in advance!
Miyako

**Comment by mkirsche** [comment]
Hi Miyako,

Thanks for your interest in Jasmine! 

1) SUPP_EXT is different from SUPP in that it is preserved across multiple merges, so if your input VCFs consist of already merged variants, then the resulting SUPP_EXT value will be the sum of the SUPP_EXT value from all of the input VCFs where a variant is present, while the SUPP value will just be the number of VCF files the variant is present in.

2) That's a good point - thank you for pointing it out! I have made the change in the Github repo so that it will be incorporated into the next release.

Best,
Melanie

**Comment by miyakokodama** [comment]
Hi Melanie,

Thanks for your reply! That would be great - I look forward to the next version :)

Thanks,
Miyako
